[package]
name = "ripgrepa-gui"
version = "1.3.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.5.4", features = [] }

[dependencies]
tauri = { version = "1.7.2", features = ["api-all"] }
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"
open = "5.3.0"
rfd = "0.14.1"
dirs = "5.0.1"
regex = "1.5.4"
chrono = "0.4.40"
winapi = { version = "0.3.9", features = ["winuser"] }
#ripgrep_all = "0.10.6"
#onig = "6"
#lazy_static = "1.4.0"
#tauri = { version = "1.0", features = ["api-all"] }
reqwest = { version = "0.12.15", features = ["json"] }
tokio = { version = "1", features = ["full"] }
filetime = "0.2.25"
sysinfo = "0.33.1"
[features]
# This feature is used for production builds or when a dev server is not specified, DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
strip = true
panic = 'abort'
debug = 0
