
interface FileTypeItem {
    include: boolean;
    type: string;
    content: string;
}

export const defaultFileTypes: FileTypeItem[] = [
    { include: true, type: 'ada', content: '*.adb *.ads' },
    { include: true, type: 'agda', content: '*.agda *.lagda' },
    { include: true, type: 'aidl', content: '*.aidl' },
    { include: true, type: 'alire', content: 'alire.toml' },
    { include: true, type: 'amake', content: '*.bp *.mk' },
    { include: true, type: 'asciidoc', content: '*.adoc *.asc *.asciidoc' },
    { include: true, type: 'asm', content: '*.S *.asm *.s' },
    { include: true, type: 'asp', content: '*.ascx *.ascx.cs *.ascx.vb *.asp *.aspx *.aspx.cs *.aspx.vb' },
    { include: true, type: 'ats', content: '*.ats *.dats *.hats *.sats' },
    { include: true, type: 'avro', content: '*.avdl *.avpr *.avsc' },
    { include: true, type: 'awk', content: '*.awk' },
    { include: true, type: 'bat', content: '*.bat' },
    { include: true, type: 'batch', content: '*.bat' },
    { include: true, type: 'bazel', content: '*.BUILD *.bazel *.bazelrc *.bzl BUILD MODULE.bazel WORKSPACE WORKSPACE.bazel' },
    { include: true, type: 'bitbake', content: '*.bb *.bbappend *.bbclass *.conf *.inc' },
    { include: true, type: 'brotli', content: '*.br' },
    { include: true, type: 'buildstream', content: '*.bst' },
    { include: true, type: 'bzip2', content: '*.bz2 *.tbz2' },
    { include: true, type: 'c', content: '*.[chH] *.[chH].in *.cats' },
    { include: true, type: 'cabal', content: '*.cabal' },
    { include: true, type: 'candid', content: '*.did' },
    { include: true, type: 'carp', content: '*.carp' },
    { include: true, type: 'cbor', content: '*.cbor' },
    { include: true, type: 'ceylon', content: '*.ceylon' },
    { include: true, type: 'clojure', content: '*.clj *.cljc *.cljs *.cljx' },
    { include: true, type: 'cmake', content: '*.cmake CMakeLists.txt' },
    { include: true, type: 'cmd', content: '*.bat *.cmd' },
    { include: true, type: 'cml', content: '*.cml' },
    { include: true, type: 'coffeescript', content: '*.coffee' },
    { include: true, type: 'config', content: '*.cfg *.conf *.config *.ini' },
    { include: true, type: 'coq', content: '*.v' },
    { include: true, type: 'cpp', content: '*.[ChH] *.[ChH].in *.[ch]pp *.[ch]pp.in *.[ch]xx *.[ch]xx.in *.cc *.cc.in *.hh *.hh.in *.inl' },
    { include: true, type: 'creole', content: '*.creole' },
    { include: true, type: 'crystal', content: '*.cr *.ecr Projectfile shard.yml' },
    { include: true, type: 'cs', content: '*.cs' },
    { include: true, type: 'csharp', content: '*.cs' },
    { include: true, type: 'cshtml', content: '*.cshtml' },
    { include: true, type: 'csproj', content: '*.csproj' },
    { include: true, type: 'css', content: '*.css *.scss' },
    { include: true, type: 'csv', content: '*.csv' },
    { include: true, type: 'cuda', content: '*.cu *.cuh' },
    { include: true, type: 'cython', content: '*.pxd *.pxi *.pyx' },
    { include: true, type: 'd', content: '*.d' },
    { include: true, type: 'dart', content: '*.dart' },
    { include: true, type: 'devicetree', content: '*.dts *.dtsi' },
    { include: true, type: 'dhall', content: '*.dhall' },
    { include: true, type: 'diff', content: '*.diff *.patch' },
    { include: true, type: 'dita', content: '*.dita *.ditamap *.ditaval' },
    { include: true, type: 'doc', content: '*.docx *.doc *.odt *.ods *.odf *.rtf *.xls *.xlsx *.pdf' },
    { include: true, type: 'docker', content: '*Dockerfile*' },
    { include: true, type: 'dockercompose', content: 'docker-compose.*.yml docker-compose.yml' },
    { include: true, type: 'dts', content: '*.dts *.dtsi' },
    { include: true, type: 'dvc', content: '*.dvc Dvcfile' },
    { include: true, type: 'ebuild', content: '*.ebuild *.eclass' },
    { include: true, type: 'edn', content: '*.edn' },
    { include: true, type: 'elisp', content: '*.el' },
    { include: true, type: 'elixir', content: '*.eex *.ex *.exs *.heex *.leex *.livemd' },
    { include: true, type: 'elm', content: '*.elm' },
    { include: true, type: 'erb', content: '*.erb' },
    { include: true, type: 'erlang', content: '*.erl *.hrl' },
    { include: true, type: 'fennel', content: '*.fnl' },
    { include: true, type: 'fidl', content: '*.fidl' },
    { include: true, type: 'fish', content: '*.fish' },
    { include: true, type: 'flatbuffers', content: '*.fbs' },
    { include: true, type: 'fortran', content: '*.F *.F77 *.F90 *.F95 *.f *.f77 *.f90 *.f95 *.pfo' },
    { include: true, type: 'fsharp', content: '*.fs *.fsi *.fsx' },
    { include: true, type: 'fut', content: '*.fut' },
    { include: true, type: 'gap', content: '*.g *.gap *.gd *.gi *.tst' },
    { include: true, type: 'gn', content: '*.gn *.gni' },
    { include: true, type: 'go', content: '*.go' },
    { include: true, type: 'gprbuild', content: '*.gpr' },
    { include: true, type: 'gradle', content: '*.gradle *.gradle.kts gradle-wrapper.* gradle.properties gradlew gradlew.bat' },
    { include: true, type: 'graphql', content: '*.graphql *.graphqls' },
    { include: true, type: 'groovy', content: '*.gradle *.groovy' },
    { include: true, type: 'gzip', content: '*.gz *.tgz' },
    { include: true, type: 'h', content: '*.h *.hh *.hpp' },
    { include: true, type: 'haml', content: '*.haml' },
    { include: true, type: 'hare', content: '*.ha' },
    { include: true, type: 'haskell', content: '*.c2hs *.cpphs *.hs *.hsc *.lhs' },
    { include: true, type: 'hbs', content: '*.hbs' },
    { include: true, type: 'hs', content: '*.hs *.lhs' },
    { include: true, type: 'html', content: '*.ejs *.htm *.html' },
    { include: true, type: 'hy', content: '*.hy' },
    { include: true, type: 'idris', content: '*.idr *.lidr' },
    { include: true, type: 'janet', content: '*.janet' },
    { include: true, type: 'java', content: '*.java *.jsp *.jspx *.properties' },
    { include: true, type: 'jinja', content: '*.j2 *.jinja *.jinja2' },
    { include: true, type: 'jl', content: '*.jl' },
    { include: true, type: 'js', content: '*.cjs *.js *.jsx *.mjs *.vue *.ts' },
    { include: true, type: 'json', content: '*.json *.sarif composer.lock' },
    { include: true, type: 'jsonl', content: '*.jsonl' },
    { include: true, type: 'julia', content: '*.jl' },
    { include: true, type: 'jupyter', content: '*.ipynb *.jpynb' },
    { include: true, type: 'k', content: '*.k' },
    { include: true, type: 'kotlin', content: '*.kt *.kts' },
    { include: true, type: 'lean', content: '*.lean' },
    { include: true, type: 'less', content: '*.less' },
    { include: true, type: 'license', content: '*[.-]LICEN[CS]E* AGPL-*[0-9]* APACHE-*[0-9]* BSD-*[0-9]* CC-BY-* COPYING COPYING[.-]* COPYRIGHT COPYRIGHT[.-]* EULA EULA[.-]* GFDL-*[0-9]* GNU-*[0-9]* GPL-*[0-9]* LGPL-*[0-9]* LICEN[CS]E LICEN[CS]E[.-]* MIT-*[0-9]* MPL-*[0-9]* NOTICE NOTICE[.-]* OFL-*[0-9]* PATENTS PATENTS[.-]* UNLICEN[CS]E UNLICEN[CS]E[.-]* agpl[.-]* gpl[.-]* lgpl[.-]* licen[cs]e licen[cs]e.*' },
    { include: true, type: 'lilypond', content: '*.ily *.ly' },
    { include: true, type: 'lisp', content: '*.el *.jl *.lisp *.lsp *.sc *.scm' },
    { include: true, type: 'lock', content: '*.lock package-lock.json' },
    { include: true, type: 'log', content: '*.log' },
    { include: true, type: 'lua', content: '*.lua' },
    { include: true, type: 'lz4', content: '*.lz4' },
    { include: true, type: 'lzma', content: '*.lzma' },
    { include: true, type: 'm4', content: '*.ac *.m4' },
    { include: true, type: 'make', content: '*.mak *.mk [Gg][Nn][Uu]makefile [Gg][Nn][Uu]makefile.am [Gg][Nn][Uu]makefile.in [Mm]akefile [Mm]akefile.am [Mm]akefile.in' },
    { include: true, type: 'mako', content: '*.mako *.mao' },
    { include: true, type: 'man', content: '*.[0-9][cEFMmpSx] *.[0-9lnpx]' },
    { include: true, type: 'markdown', content: '*.markdown *.md *.mdown *.mdwn *.mdx *.mkd *.mkdn' },
    { include: true, type: 'matlab', content: '*.m' },
    { include: true, type: 'meson', content: 'meson.build meson.options meson_options.txt' },
    { include: true, type: 'minified', content: '*.min.css *.min.html *.min.js' },
    { include: true, type: 'mint', content: '*.mint' },
    { include: true, type: 'mk', content: 'mkfile' },
    { include: true, type: 'ml', content: '*.ml' },
    { include: true, type: 'motoko', content: '*.mo' },
    { include: true, type: 'msbuild', content: '*.csproj *.fsproj *.proj *.props *.sln *.targets *.vcxproj' },
    { include: true, type: 'nim', content: '*.nim *.nimble *.nimf *.nims' },
    { include: true, type: 'nix', content: '*.nix' },
    { include: true, type: 'objc', content: '*.h *.m' },
    { include: true, type: 'objcpp', content: '*.h *.mm' },
    { include: true, type: 'ocaml', content: '*.ml *.mli *.mll *.mly' },
    { include: true, type: 'org', content: '*.org *.org_archive' },
    { include: true, type: 'pants', content: 'BUILD' },
    { include: true, type: 'pascal', content: '*.dpr *.inc *.lpr *.pas *.pp' },
    { include: true, type: 'picture', content: '*.[jJ][pP][gG] *.[jJ][pP][eE][gG] *.[bB][mM][pP] *.[pP][nN][gG] *.[gG][iI][fF] *.jpg *.tiff *.raw *.svg *.psd *.eps' },
    { include: true, type: 'pdf', content: '*.pdf' },
    { include: true, type: 'perl', content: '*.PL *.perl *.pl *.plh *.plx *.pm *.t' },
    { include: true, type: 'php', content: '*.php *.php3 *.php4 *.php5 *.php7 *.php8 *.pht *.phtml' },
    { include: true, type: 'po', content: '*.po' },
    { include: true, type: 'pod', content: '*.pod' },
    { include: true, type: 'postscript', content: '*.eps *.ps' },
    { include: true, type: 'prolog', content: '*.P *.pl *.pro *.prolog' },
    { include: true, type: 'protobuf', content: '*.proto' },
    { include: true, type: 'ps', content: '*.cdxml *.ps1 *.ps1xml *.psd1 *.psm1' },
    { include: true, type: 'puppet', content: '*.epp *.erb *.pp *.rb' },
    { include: true, type: 'purs', content: '*.purs' },
    { include: true, type: 'python', content: '*.py *.pyi' },
    { include: true, type: 'qmake', content: '*.prf *.pri *.pro' },
    { include: true, type: 'qml', content: '*.qml' },
    { include: true, type: 'r', content: '*.R *.Rmd *.Rnw *.r' },
    { include: true, type: 'racket', content: '*.rkt' },
    { include: true, type: 'raku', content: '*.p6 *.pl6 *.pm6 *.raku *.rakudoc *.rakumod *.rakutest' },
    { include: true, type: 'rdoc', content: '*.rdoc' },
    { include: true, type: 'readme', content: '*README README*' },
    { include: true, type: 'reasonml', content: '*.re *.rei' },
    { include: true, type: 'red', content: '*.r *.red *.reds' },
    { include: true, type: 'rescript', content: '*.res *.resi' },
    { include: true, type: 'robot', content: '*.robot' },
    { include: true, type: 'rst', content: '*.rst' },
    { include: true, type: 'ruby', content: '*.gemspec *.rb *.rbw .irbrc Gemfile Rakefile config.ru' },
    { include: true, type: 'rust', content: '*.rs' },
    { include: true, type: 'sass', content: '*.sass *.scss' },
    { include: true, type: 'scala', content: '*.sbt *.scala' },
    { include: true, type: 'sh', content: '*.bash *.bashrc *.csh *.cshrc *.ksh *.kshrc *.sh *.tcsh *.zsh .bash_login .bash_logout .bash_profile .bashrc .cshrc .kshrc .login .logout .profile .tcshrc .zlogin .zlogout .zprofile .zshenv .zshrc bash_login bash_logout bash_profile bashrc profile zlogin zlogout zprofile zshenv zshrc' },
    { include: true, type: 'slim', content: '*.skim *.slim *.slime' },
    { include: true, type: 'smarty', content: '*.tpl' },
    { include: true, type: 'sml', content: '*.sig *.sml' },
    { include: true, type: 'solidity', content: '*.sol' },
    { include: true, type: 'soy', content: '*.soy' },
    { include: true, type: 'spark', content: '*.spark' },
    { include: true, type: 'spec', content: '*.spec' },
    { include: true, type: 'sql', content: '*.psql *.sql' },
    { include: true, type: 'stylus', content: '*.styl' },
    { include: true, type: 'sv', content: '*.h *.sv *.svh *.v *.vg' },
    { include: true, type: 'svg', content: '*.svg' },
    { include: true, type: 'swift', content: '*.swift' },
    { include: true, type: 'swig', content: '*.def *.i' },
    { include: true, type: 'systemd', content: '*.automount *.conf *.device *.link *.mount *.path *.scope *.service *.slice *.socket *.swap *.target *.timer' },
    { include: true, type: 'taskpaper', content: '*.taskpaper' },
    { include: true, type: 'tcl', content: '*.tcl' },
    { include: true, type: 'tex', content: '*.bib *.cls *.dtx *.ins *.ltx *.sty *.tex' },
    { include: true, type: 'texinfo', content: '*.texi' },
    { include: true, type: 'textile', content: '*.textile' },
    { include: true, type: 'tf', content: '*.auto.tfvars *.auto.tfvars.json *.terraform.lock.hcl *.terraformrc *.tf *.tf.json *.tfrc terraform.rc terraform.tfvars terraform.tfvars.json' },
    { include: true, type: 'thrift', content: '*.thrift' },
    { include: true, type: 'toml', content: '*.toml Cargo.lock' },
    { include: true, type: 'twig', content: '*.twig' },
    { include: true, type: 'txt', content: '*.txt' },
    { include: true, type: 'typescript', content: '*.cts *.mts *.ts *.tsx' },
    { include: true, type: 'typoscript', content: '*.ts *.typoscript' },
    { include: true, type: 'usd', content: '*.usd *.usda *.usdc' },
    { include: true, type: 'v', content: '*.v *.vsh' },
    { include: true, type: 'vala', content: '*.vala' },
    { include: true, type: 'vb', content: '*.vb' },
    { include: true, type: 'vcl', content: '*.vcl' },
    { include: true, type: 'verilog', content: '*.sv *.svh *.v *.vh' },
    { include: true, type: 'vhdl', content: '*.vhd *.vhdl' },
    { include: true, type: 'vim', content: '*.vim .gvimrc .vimrc _gvimrc _vimrc gvimrc vimrc' },
    { include: true, type: 'vimscript', content: '*.vim .gvimrc .vimrc _gvimrc _vimrc gvimrc vimrc' },
    { include: true, type: 'webidl', content: '*.idl *.webidl *.widl' },
    { include: true, type: 'wiki', content: '*.mediawiki *.wiki' },
    { include: true, type: 'xml', content: '*.dtd *.rng *.sch *.xhtml *.xjb *.xml *.xml.dist *.xsd *.xsl *.xslt' },
    { include: true, type: 'xz', content: '*.txz *.xz' },
    { include: true, type: 'yacc', content: '*.y' },
    { include: true, type: 'yaml', content: '*.yaml *.yml' },
    { include: true, type: 'yang', content: '*.yang' },
    { include: true, type: 'z', content: '*.Z' },
    { include: true, type: 'zig', content: '*.zig' },
    { include: true, type: 'zip', content: '*.[zZ][iI][pP] *.[rR][aA][rR] *.gz *.tgz *.arj *.7z *.tar *.bz2 *.tbz2 *.Z *.lzh *.ace *.jar *.tar.zst' },
    { include: true, type: 'zsh', content: '*.zsh .zlogin .zlogout .zprofile .zshenv .zshrc zlogin zlogout zprofile zshenv zshrc' },
    { include: true, type: 'zstd', content: '*.zst *.zstd' }

    // Add more items as needed
];